### ISSUE TITLE
Bundle.main.version shows build number

### ISSUE THREAD

**Issue by twodayslate** [mrackwitz/Version#46]
`Bundle.main.version` shows the build number with `kCFBundleVersionKey` when it should show `Bundle.main.shortVersion + "-" + Bundle.main.version`

Proposing `version` be renamed to `build`

Let me know if my project is just wrong but I think my understanding of the keys is correct.

**Comment by regexident** [comment]
`Bundle.version` is merely a convenience wrapper around Apple's [`kCFBundleVersionKey`](https://developer.apple.com/documentation/corefoundation/kcfbundleversionkey):

```swift
extension Bundle {
    /// The marketing version number of the bundle.
    public var version : Version? {
        return self.versionFromInfoDicitionary(forKey: String(kCFBundleVersionKey))
    }

    // ...
}
```
[Source](https://github.com/mrackwitz/Version/blob/master/Version/Version.swift#L257-L259)

As such if `Bundle.main.version` ends up showing just a build number then it looks like your project is providing a build number, where it should be providing a whole version number?

**Comment by twodayslate** [comment]
This is what I have in my project.
<img width="528" alt="Screen Shot 2019-10-16 at 3 44 58 PM" src="https://user-images.githubusercontent.com/1085707/66953163-f2d7ce00-f02b-11e9-85d7-2bd8f8a00b17.png">
This is what a default Xcode 11 project includes:
<img width="524" alt="Screen Shot 2019-10-16 at 3 47 29 PM" src="https://user-images.githubusercontent.com/1085707/66953388-624dbd80-f02c-11e9-900e-62bc75fe405d.png">
And when you change the values in the project editor it changes to this:
<img width="528" alt="Screen Shot 2019-10-16 at 3 44 58 PM" src="https://user-images.githubusercontent.com/1085707/66953321-477b4900-f02c-11e9-9d29-6ac34c530115.png">


[This SO post](https://stackoverflow.com/a/7608711/193772) seems to match the above.

**Comment by lottadot** [comment]
Note: Xcode 11 changed some things wrt versioning. You should consider not changing your versioning information through the Xcode IDE, but rather use `agvtool` (imho). See https://github.com/fastlane/fastlane/issues/15322

**Comment by jeff-h** [comment]
Personally I think @twodayslate is right. I've used Xcode's Version & Build GUI:

<img width="115" alt="image" src="https://user-images.githubusercontent.com/841871/82134465-589f6900-984c-11ea-8d06-cd33f0f40e66.png">

Version provides that as:
`Bundle.main.version` = Optional(1)
`Bundle.main.shortVersion` = Optional(1.0.12)

So I also think `Bundle.main.version` would be better renamed `Bundle.main.build`. I think the underlying problem here is that Apple have misnamed `kCFBundleVersionKey`, so I do understand the current name is consistent with that, but IMO it's a consistency with something incorrect lol
